module.exports = {
  table_exists: "ResourceInUseException",
  TABLE_NAME: "VSpace_Local",
  // TABLE_NAME:'test',
  id: "id is required",
  TITLE: "title is required",
  MESSAGE: "message is required",
  attendees: "attendees are required",
  attendeesEmailMissing: "Email is missing in attendees array",
  status: "status is required",
  STATUS_CODE_400: "400",
  SUCCESS: "SUCCESS",
  domainName: "localhost",
  stage: "local",
  Sockets: "SOCKETS#",
  gameId: "game id is required",
  tournamentId: "tournament id is required",
  roundId: "round id is required",
  matchId: "match id is required",
  teamLead: "teamLead is required",
  players: "players are required",
  players2: "email field is required in every player object",
  score: "score is required",
  level: "level is required",
  fee: "fee is required",
  bundleId: "bundleId is required",
  playerGreaterError: "No of players provided are greate then total team.",
  PlayerAlreadyRegsitered: "Some of players are already in another team.",
  NameNotAvailable: "Another team exixts with same name",
  prize: "prize is required",
  registrationTime: "registrationTime is requied",
  registrationTime2: "registrationTime should be an integer and a time stamp",
  type: "type is required",
  link: "link is required",
  date: "date is required",
  teams: "teams data is required",
  SESSION_EXPIRED: "Session Expired",
  endDate: "end Date is required",
  startDate: "start Date is required",
  no_of_teams: "no. of team is required",
  no_of_players: "no. of players is required",
  DATA_ADDED: "Data added successfully",
  DATA_UPDATED: "Data updated successfully",
  Name: "name is required",
  VENDOR_ID: "Vendor id is required",
  BUNDLE_ID_IOS: "IOS Bundle id is required",
  BUNDLE_ID_ANDROID: "Android Bundle id is required",
  STORE_ID_IOS: "IOS Store id is required",
  STORE_ID_ANDROID: "Android Store id is required",
  PLATEFORM: "Platform is required",
  CURRENCY: "Currency is required",
  LEADERBOARD: "Leaderboard is required",
  NOTIFICATIONSENT: "Notification sent successfully",
  ENGINE: "Engine is required",
  TURNAMENRNOTIFICATIONTITLE: "Tournament Registeration alert",
  TURNAMENRNOTIFICATIONBODY: "You have bee registered into",
  NEWTOURNAMENTALERT: "New Tournament alert",
  NEWTOURNAMENTBODY: "New Tournament",
  MATCHSTATUSTITLE: "Match Status alert",
  MATCHWINNERSTATUSBODY: "Conguratulations, you have won the match",
  MATCHLOSERSTATUSBODY: "Alas!, you have lost the match",
  TOURNAMENTREMINDERTITLE: "Tournament remainder  alert",
  GAME_ICON: "Game icon is required",
  password: "Password is required",
  CERTIFICATE: "Certificate is required",
  assemblaId: "Assembla id is required",
  leadCount: "Lead count is required",
  sequenceId: "Sequence id is required",
  errorsavingdata: "error in saving data",
  savedata: "Data save succesfully",
  INVALID_REQUEST: "Invalid request",
  ErrorTryCatch: "Exception Handing",
  NoUserFound: "No User Found",
  emailIsRequired: "Email is Required",
  emailNotValid: "Email Not Valid",
  ASSIGNEDTO: "Assigned To is required",
  COUNTRY: "Country is required",
  CURRENT_URL: "Current URL is required",
  localStage: "local",
  deployedStage: "live",
  MATCH_COMPLETED: "Match already completed",
  ROUND_ALREADY_PLAYED: "This round is already played",
  USERNAME: "Name is required",
  ROLE_REQUIRED: "Role is required",
  COMPLETED: "Completed",
  ACTIVE: "Active",
  DELETED: "Deleted",
  ACCEPTED: "Accepted",
  REJECTED: "Rejected",
  INVITATIONACCEPTED: "Invitation has accepted",
  INVITATIONREJECTED: "Invitation has rejected",
  ACCEPTED: "Accepted",
  STARTED: "Started",
  DISABLED: "Disabled",
  DATA_NOT_FOUND: "Data not Found!",
  PHONE: "Phone is required",
  RECORD_CREATED: "user has been created successfully",
  DATA_NOT_PROVIDED: "Request Data not provided!",
  TAGS: "Tags are required",
  TOURNAMENTDOESNOTEXIST: "Tournament Data not found",
  TEAMSNOTREGISTEREDCOMPLETELY: "Teams are not registered Completely",
  MATCHSTATUSUPDATED: "Match has ended!",
  Description: "Description is required",
  SPACE_ID: "xxxx",
  ALREADYPLAYEDPREVIOUSROUNDMATCH: "Already played previous round and lost",
  ALREADYPLAYEDTHISROUNDMATCH: "Already Played this match of this round",
  ALREADYPLAYEDTHISROUNDMATCHLOST:
    "Already Played this match of this round and lost",
  SPACE_ID_REQUIRED: "Space Id is required",
  SPACE_IS_REQUIRED: "Space is required",
  ASSEMLA_DUMMY_ID: "xxxx",
  ASSEMLA_SUMARY: "Campaign Leads",
  SUMARY: "Summary is required",
  TEAMSNOTREGISTERED: "Teams not registered for this tournament yet!",
  TOURNAMENT_TIME_PASSED: "Tournament time is passed",
  ROUND_TIME_PASSED: "Round time is passed",
  ROUNDCOMPLETED: "Round has already been completed",
  ASSIGN_TO_ID: "AssignedTo id is required",
  KEY: "xxxx",
  SECRET_KEY: "xxxx",
  ADMIN_FOR_EMAIL: "xxxx",
  ADMIN_PASSWORD: "xxxx",
  STATUS: "status is required",
  STATUS_CODE_501: "501",
  STATUS_CODE_500: "500",
  STATUS_CODE_200: "200",
  STATUS_CODE_205: "205",
  INACTIVE_ACCOUNR: "Inactive Account",
  WRONG_PASSWORD: "Wrong password",
  RECORD_DELETED: "Record deleted!",
  LeadError: "lead cannot not be in members array",
  SOMETHING_WENT_WRONG: "Something went wrong!",
  ROUNDS_FIELDS_TOUPDATE: [
    "fee",
    "prize",
    "idConAuto",
    "status",
    "startDate",
    "endDate",
    "roundNo",
  ],
  PLAYERS_FIELDS_TOUPDATE: [
    "name",
    "email",
    "score",
    "status",
    "level",
    "GameId",
    "isLeader",
  ],
  MATCH_TEAM_FIELDS_TOUPDATE: ["status", "score"],
  TEAMS_FIELDS_TOUPDATE: ["status"],
  HEADERS: {
    "Content-Type": "application/json",
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "Content-Type",
  },
  STATUS_CODE_403: "403",
  STATUS_CODE_402: "402",
  STATUS_CODE_401: "401",
  Password: "Password is required",
  PasswordTwo: "Password should contain atleast one Integer",
  PasswordTwos: "Password should contain atleast 8 characters",
  Role: "User role is required",
  Email: "email is required",
  Phone: "phone is required",
  PhoneSize: "Phone number should be 11 numbers long",
  TEAMLIMITEXCEEDED: "Tournament teams limit exceeded!",
  region: "xxxx",
  SequelizeUniqueConstraintError: "SequelizeUniqueConstraintError",
  token: "access",
  PhoneTwo: "Phone should only contain numbers",
  pooldata: {
    UserPoolId: "xxxx",
    ClientId: "xxxx",
  },
  teamPlayer: {
    invited: "Invited",
    Accepted: "Accepted",
    Rejected: "Rejected",
  },
  RegisterOver: "Registration Time is over",
  tournamentRegistertrationLimit: 24, // in hours,
  LeadNotFound: "Lead is not in our record",
  NotAllPlayerRegistered: "Not All players are registered",
  DeleteLeaderError: "Cant Delete the leader of team ",
  NoRecordFoundError: "No record found",
  isLeader: "false",
  DefaultServerKey: "xxxx",
  unRegisterValidation: {
    tournamentId: "tournament id required",
    teamId: "team id required",
    playerId: "player id required",
  },
  noPlayerFound: "No player Found for this Game",
  AUTH_HEADERS: {
    "Content-Type": "application/json",
    "X-Api-Key": "xxxx",
    "X-Api-Secret": "xxxx",
    "Access-Control-Allow-Origin": "*",
  },
  APIurl: "https://api.assembla.com/v1",
  Space_Details: {
    xxxx: "Sales-Marketing", //
    xxxx: "Geni.Team Web-Apps", //
    xxxx: "TapGames", //
    xxxx: "Arcade Games", //
    xxxx: "tgb-graphics", //
    xxxx: "PuzzleCorp", //
    xxxx: "WAO-Inc", //
    xxxx: "ZnK Games", //
    xxxx: "Geniteam-Meshal", //
    xxxx: "Analysis-Marketing", //
    xxxx: "General", //
  },
  InvalidPassword: "Invalid Email/Password",
  ADMIN_EMAIL: "xxxx",

  ADMIN_PANEL_URL:
    "https://www.dropbox.com/s/nvtuf77up5xwqo0/Virtual%20Space%20-%20Requirement%20Doc%20v1.0.docx?dl=0",

  auth: {
    user: "xxxx",
    pass: "xxxx",
  },
};
